baseURL: "https://rrvll.netlify.app/"
languageCode: en-us
title: Román Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get to know me
    subtitle: A website created to showcase what I have been up to lately!
    title: Hi, my name is Roman Vazquez Lorenzo
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: NW14SA
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: romanv.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+34) 619 469 810
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/romanvazquezl/
      - icon: fa-github
        label: GitHub
        url: https://github.com/RomanVazquezL
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/roman-vazquez-lorenzo
  image: ''
  name: Roman
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/roman_vazquez_lorenzo
      - name: My Education
        url: blogs/my_education
      - name: My Experience
        url: blogs/my_experience
      - name: My Objectives
        url: blogs/my_objectives
      - name: My Projects
        url: blogs/my_projects
      - name: My Resume
        url: blogs/my_resume
    menu: Menu
    subtitle: ByRoman
    title: My Website
  tiles:
    enable: yes
    showcase:
      - image: Sada_boats.jpg
        subtitle: This is where I come from
        title: About me
        url: blogs/roman_vazquez_lorenzo
      - image: Interra.jpg
        subtitle: This is where I have been taught what I know
        title: My Education
        url: blogs/my_education
      - image: Rope_Uganda.jpg
        subtitle: This is how I have applied what I have been taught
        title: My Experience
        url: blogs/my_experience
      - image: AM_interra.jpg
        subtitle: My final year engineering thesis
        title: Machine Learning for Additive Manufacturing
        url: blogs/my_projects
      - image: Be_Disciplined.jpg
        subtitle: This is where I want to go
        title: My objectives
        url: blogs/my_objectives
      - image: uganda_mirror.jpg
        subtitle: Download it and reach out if interested
        title: My Resume
        url: blogs/my_resume
  two:
    buttonText: rrvll
    enable: yes
    subtitle: "All the photos on my website have been taken by me. Click below and check these and more in my VSCO account! "
    title: My photos
    image: uganda_bano.jpg
    url: https://vsco.co/rrvll/gallery
