baseURL: "https://rrvll.netlify.app/"
languageCode: en-us
title: Román Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get to know me
    subtitle: 
      A website created to showcase what I have been up to lately!
      title: Hi, my name is Román Vázquez Lorenzo
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: NW14SA
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: romanv.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+34) 619 469 810
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/romanvazquezl/
      - icon: fa-github
        label: GitHub
        url: https://github.com/RomanVazquezL
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/roman-vazquez-lorenzo
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: ByRoman
    title: My Website
  tiles:
    enable: yes
    showcase:
      - image: 2018-08-28 05.26.50 1.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: AboutMe
        url: blogs/roman_vazquez_lorenzo
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: My Education
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: My Education
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: My projects
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: 
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: My Resumé
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Experience to learn."
    title: Massa libero
    url: blogs
